"""
ap-common: Shared functionality for astrophotography tools

Generated By: Cursor (Claude Sonnet 4.5)
"""

from ap_common.fits import get_fits_headers, get_xisf_headers, get_file_headers
from ap_common.normalization import (
    normalize_headers,
    normalize_date,
    normalize_datetime,
    normalize_filterName,
    normalize_target_name,
    normalize_filename,
    denormalize_header,
    FILTER_NORMALIZATION_DATA,
    CONSTANT_NORMALIZATION_DATA,
)
from ap_common.filesystem import move_file, copy_file, delete_empty_directories
from ap_common.metadata import (
    get_metadata,
    enrich_metadata,
    get_filtered_metadata,
    filter_metadata,
)
from ap_common.utils import replace_env_vars, camelCase, get_filenames
from ap_common.progress import progress_iter, ProgressTracker
from ap_common.logging_config import setup_logging, get_logger
from ap_common.constants import (
    # Directory constants
    DIRECTORY_ACCEPT,
    # FITS Header constants
    HEADER_DATE_OBS,
    HEADER_IMAGETYP,
    HEADER_TELESCOP,
    HEADER_FOCRATIO,
    HEADER_INSTRUME,
    HEADER_OBJECT,
    HEADER_FILTER,
    HEADER_EXPOSURE,
    HEADER_EXPTIME,
    HEADER_EXP,
    HEADER_CCD_TEMP,
    HEADER_SETTEMP,
    HEADER_SET_TEMP,
    HEADER_SITELAT,
    HEADER_SITELONG,
    HEADER_OBSGEO_B,
    HEADER_OBSGEO_L,
    HEADER_READOUTM,
    # Normalized header names
    NORMALIZED_HEADER_DATE,
    NORMALIZED_HEADER_DATETIME,
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_OPTIC,
    NORMALIZED_HEADER_FOCAL_RATIO,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_TARGETNAME,
    NORMALIZED_HEADER_FILTER,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_TEMP,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_LATITUDE,
    NORMALIZED_HEADER_LONGITUDE,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_PANEL,
    NORMALIZED_HEADER_FILENAME,
    NORMALIZED_HEADER_HFR,
    NORMALIZED_HEADER_STARS,
    NORMALIZED_HEADER_RMSAC,
    # Image type constants - Raw frames
    TYPE_LIGHT,
    TYPE_DARK,
    TYPE_FLAT,
    TYPE_BIAS,
    # Image type constants - Master frames
    TYPE_MASTER_LIGHT,
    TYPE_MASTER_DARK,
    TYPE_MASTER_FLAT,
    TYPE_MASTER_BIAS,
    # Calibration type lists
    CALIBRATION_TYPES,
    MASTER_CALIBRATION_TYPES,
    ALL_CALIBRATION_TYPES,
    # File extension constants
    FILE_EXTENSION_FITS,
    FILE_EXTENSION_XISF,
    FILE_EXTENSION_CR2,
    DEFAULT_FITS_PATTERN,
    DEFAULT_XISF_PATTERN,
    DEFAULT_CR2_PATTERN,
    DEFAULT_IMAGE_PATTERNS,
)

__all__ = [
    # FITS functions
    "get_fits_headers",
    "get_xisf_headers",
    "get_file_headers",
    # Normalization functions
    "normalize_headers",
    "normalize_date",
    "normalize_datetime",
    "normalize_filterName",
    "normalize_target_name",
    "normalize_filename",
    "denormalize_header",
    "FILTER_NORMALIZATION_DATA",
    "CONSTANT_NORMALIZATION_DATA",
    # Filesystem functions
    "move_file",
    "copy_file",
    "delete_empty_directories",
    # Metadata functions
    "get_metadata",
    "enrich_metadata",
    "get_filtered_metadata",
    "filter_metadata",
    # Utility functions
    "replace_env_vars",
    "camelCase",
    "get_filenames",
    # Progress utilities
    "progress_iter",
    "ProgressTracker",
    # Logging functions
    "setup_logging",
    "get_logger",
    # Directory constants
    "DIRECTORY_ACCEPT",
    # FITS Header constants
    "HEADER_DATE_OBS",
    "HEADER_IMAGETYP",
    "HEADER_TELESCOP",
    "HEADER_FOCRATIO",
    "HEADER_INSTRUME",
    "HEADER_OBJECT",
    "HEADER_FILTER",
    "HEADER_EXPOSURE",
    "HEADER_EXPTIME",
    "HEADER_EXP",
    "HEADER_CCD_TEMP",
    "HEADER_SETTEMP",
    "HEADER_SET_TEMP",
    "HEADER_SITELAT",
    "HEADER_SITELONG",
    "HEADER_OBSGEO_B",
    "HEADER_OBSGEO_L",
    "HEADER_READOUTM",
    # Normalized header names
    "NORMALIZED_HEADER_DATE",
    "NORMALIZED_HEADER_DATETIME",
    "NORMALIZED_HEADER_TYPE",
    "NORMALIZED_HEADER_OPTIC",
    "NORMALIZED_HEADER_FOCAL_RATIO",
    "NORMALIZED_HEADER_CAMERA",
    "NORMALIZED_HEADER_TARGETNAME",
    "NORMALIZED_HEADER_FILTER",
    "NORMALIZED_HEADER_EXPOSURESECONDS",
    "NORMALIZED_HEADER_TEMP",
    "NORMALIZED_HEADER_SETTEMP",
    "NORMALIZED_HEADER_LATITUDE",
    "NORMALIZED_HEADER_LONGITUDE",
    "NORMALIZED_HEADER_READOUTMODE",
    "NORMALIZED_HEADER_PANEL",
    "NORMALIZED_HEADER_FILENAME",
    "NORMALIZED_HEADER_HFR",
    "NORMALIZED_HEADER_STARS",
    "NORMALIZED_HEADER_RMSAC",
    # Image type constants - Raw frames
    "TYPE_LIGHT",
    "TYPE_DARK",
    "TYPE_FLAT",
    "TYPE_BIAS",
    # Image type constants - Master frames
    "TYPE_MASTER_LIGHT",
    "TYPE_MASTER_DARK",
    "TYPE_MASTER_FLAT",
    "TYPE_MASTER_BIAS",
    # Calibration type lists
    "CALIBRATION_TYPES",
    "MASTER_CALIBRATION_TYPES",
    "ALL_CALIBRATION_TYPES",
    # File extension constants
    "FILE_EXTENSION_FITS",
    "FILE_EXTENSION_XISF",
    "FILE_EXTENSION_CR2",
    "DEFAULT_FITS_PATTERN",
    "DEFAULT_XISF_PATTERN",
    "DEFAULT_CR2_PATTERN",
    "DEFAULT_IMAGE_PATTERNS",
]
