"""
ap-common: Shared functionality for astrophotography tools

Generated By: Cursor (Claude Sonnet 4.5)
"""

from ap_common.fits import get_fits_headers, get_xisf_headers, get_file_headers
from ap_common.normalization import (
    normalize_headers,
    normalize_date,
    normalize_datetime,
    normalize_filterName,
    normalize_target_name,
    normalize_filename,
    denormalize_header,
    FILTER_NORMALIZATION_DATA,
    CONSTANT_NORMALIZATION_DATA,
)
from ap_common.filesystem import move_file, copy_file, delete_empty_directories
from ap_common.metadata import (
    get_metadata,
    enrich_metadata,
    get_filtered_metadata,
    filter_metadata,
)
from ap_common.utils import replace_env_vars, camelCase, get_filenames
from ap_common.progress import progress_iter, ProgressTracker

__all__ = [
    # FITS functions
    "get_fits_headers",
    "get_xisf_headers",
    "get_file_headers",
    # Normalization functions
    "normalize_headers",
    "normalize_date",
    "normalize_datetime",
    "normalize_filterName",
    "normalize_target_name",
    "normalize_filename",
    "denormalize_header",
    "FILTER_NORMALIZATION_DATA",
    "CONSTANT_NORMALIZATION_DATA",
    # Filesystem functions
    "move_file",
    "copy_file",
    "delete_empty_directories",
    # Metadata functions
    "get_metadata",
    "enrich_metadata",
    "get_filtered_metadata",
    "filter_metadata",
    # Utility functions
    "replace_env_vars",
    "camelCase",
    "get_filenames",
    # Progress utilities
    "progress_iter",
    "ProgressTracker",
]
