"""
Utility functions: environment variable replacement, string conversion, and file finding.

Generated By: Cursor (Claude Sonnet 4.5)
"""

import os
import re
import zipfile


def replace_env_vars(input: str):
    """
    Replaces environment variable placeholders in a string with their actual values from the OS environment.

    Args:
        input: String that may contain environment variable placeholders like %VARNAME%

    Returns:
        String with environment variables replaced, or None if input is None
    """
    if input is None:
        return None
    output = input
    output_uc = input.upper()
    for e in os.environ.items():
        k = f"%{e[0]}%"
        v = e[1]
        while k in output_uc:
            # env vars are uppercase but ignore case when used.  use slices to do replacing.
            k_start = output_uc.find(k)
            output = output[:k_start] + v + output[k_start + len(k) :]
            output_uc = output.upper()
    return output


# https://stackoverflow.com/questions/8347048/how-to-convert-string-to-title-case-in-python
def camelCase(st):
    """
    Convert a string to camelCase, removing non-alphanumeric characters and capitalizing each word except the first.

    Args:
        st: String to convert

    Returns:
        camelCase string
    """
    output = "".join(x for x in st.title() if x.isalnum())
    return output[0].lower() + output[1:]


def get_filenames(
    dirs: list, patterns: list = None, recursive: bool = False, zips: bool = False
):
    """
    Returns a list of filenames in the given directories matching the provided patterns.
    Supports recursive search and ZIP archive extraction.

    Args:
        dirs: List of directories to search
        patterns: List of regex patterns to match (defaults to [r".*[.]fits$"])
        recursive: Whether to search recursively
        zips: Whether to search inside ZIP files

    Returns:
        List of matching file paths
    """
    if patterns is None:
        patterns = [r".*\.fits$"]

    filenames = []
    for pattern in patterns:
        for dir in dirs:
            dir = replace_env_vars(dir)
            if not recursive:
                for filename in os.listdir(dir):
                    filename_path = os.path.join(dir, filename)
                    # Check if it matches the pattern or is a zip file
                    if re.search(pattern, filename) or (
                        zips and zipfile.is_zipfile(filename_path)
                    ):
                        # found a matching file or found a zip file
                        if zips and zipfile.is_zipfile(filename_path):
                            # Process ZIP archive
                            with zipfile.ZipFile(filename_path, "r") as archive:
                                for zip_filename in (
                                    filename
                                    for filename in archive.filelist
                                    if re.search(pattern, filename)
                                ):
                                    # add each contained filename that matches the pattern
                                    filenames.append(
                                        os.path.join(
                                            filename_path, zip_filename.filename
                                        )
                                    )
                        else:
                            # not a zip, simply add it
                            filenames.append(filename_path)
            else:
                for root, _, f_names in os.walk(dir):
                    for filename in (
                        filename for filename in f_names if re.search(pattern, filename)
                    ):
                        # special cases to ignore...
                        if "_stash" in root:
                            continue
                        filenames.append(os.path.join(root, filename))
    return filenames
