"""
Unit tests for ap_common.utils module.

Generated By: Cursor (Claude Sonnet 4.5)
"""

import pytest
import os
from pathlib import Path
from ap_common.utils import (
    build_profile,
    replace_env_vars,
    resolve_path,
    camelCase,
    get_filenames,
)


class TestBuildProfile:
    """Tests for build_profile function."""

    def test_all_keys_present(self):
        """Test profile is built when all keys are present."""
        headers = {
            "optic": "Refractor",
            "focal_ratio": "5.6",
            "camera": "Camera1",
        }
        assert build_profile(headers) == "Refractor@f5.6+Camera1"

    def test_missing_optic_has_camera(self):
        """Test returns just camera when optic is missing."""
        headers = {
            "focal_ratio": "5.6",
            "camera": "Camera1",
        }
        assert build_profile(headers) == "Camera1"

    def test_missing_focal_ratio(self):
        """Test returns optic+camera when focal_ratio is missing."""
        headers = {
            "optic": "Refractor",
            "camera": "Camera1",
        }
        assert build_profile(headers) == "Refractor+Camera1"

    def test_missing_camera(self):
        """Test returns optic@ffocal_ratio when camera is missing."""
        headers = {
            "optic": "Refractor",
            "focal_ratio": "5.6",
        }
        assert build_profile(headers) == "Refractor@f5.6"

    def test_only_optic(self):
        """Test returns just optic when only optic is present."""
        headers = {
            "optic": "Refractor",
        }
        assert build_profile(headers) == "Refractor"

    def test_only_camera(self):
        """Test returns just camera when only camera is present."""
        headers = {
            "camera": "Camera1",
        }
        assert build_profile(headers) == "Camera1"

    def test_only_focal_ratio(self):
        """Test returns None when only focal_ratio is present (doesn't make sense alone)."""
        headers = {
            "focal_ratio": "5.6",
        }
        assert build_profile(headers) is None

    def test_optic_is_none(self):
        """Test optic None is skipped, returns camera."""
        headers = {
            "optic": None,
            "focal_ratio": "5.6",
            "camera": "Camera1",
        }
        assert build_profile(headers) == "Camera1"

    def test_focal_ratio_is_none(self):
        """Test focal_ratio None is skipped."""
        headers = {
            "optic": "Refractor",
            "focal_ratio": None,
            "camera": "Camera1",
        }
        assert build_profile(headers) == "Refractor+Camera1"

    def test_camera_is_none(self):
        """Test camera None is skipped."""
        headers = {
            "optic": "Refractor",
            "focal_ratio": "5.6",
            "camera": None,
        }
        assert build_profile(headers) == "Refractor@f5.6"

    def test_empty_dict(self):
        """Test returns None for empty dict."""
        assert build_profile({}) is None

    def test_all_none(self):
        """Test returns None when all values are None."""
        headers = {
            "optic": None,
            "focal_ratio": None,
            "camera": None,
        }
        assert build_profile(headers) is None

    def test_extra_keys_ignored(self):
        """Test that extra keys don't affect the result."""
        headers = {
            "optic": "Refractor",
            "focal_ratio": "5.6",
            "camera": "Camera1",
            "type": "LIGHT",
            "targetname": "M42",
        }
        assert build_profile(headers) == "Refractor@f5.6+Camera1"


class TestReplaceEnvVars:
    """Tests for replace_env_vars function."""

    def test_none_input(self):
        """Test that None input returns None."""
        assert replace_env_vars(None) is None

    def test_no_env_vars(self):
        """Test string without environment variables."""
        assert replace_env_vars("simple string") == "simple string"

    def test_with_env_var(self, monkeypatch):
        """Test replacement of environment variable."""
        monkeypatch.setenv("TEST_VAR", "test_value")
        assert replace_env_vars("%TEST_VAR%") == "test_value"

    def test_with_path_env_var(self, monkeypatch):
        """Test replacement in a path string."""
        monkeypatch.setenv("HOME", "/home/user")
        result = replace_env_vars("%HOME%/Documents")
        assert result == "/home/user/Documents"

    def test_case_insensitive(self, monkeypatch):
        """Test that environment variable matching is case-insensitive."""
        monkeypatch.setenv("TEST_VAR", "test_value")
        assert replace_env_vars("%test_var%") == "test_value"
        assert replace_env_vars("%TEST_VAR%") == "test_value"
        assert replace_env_vars("%Test_Var%") == "test_value"

    def test_multiple_replacements(self, monkeypatch):
        """Test multiple environment variable replacements."""
        monkeypatch.setenv("VAR1", "value1")
        monkeypatch.setenv("VAR2", "value2")
        result = replace_env_vars("%VAR1% and %VAR2%")
        assert result == "value1 and value2"

    def test_mixed_case_in_string(self, monkeypatch):
        """Test replacement when env var appears in mixed case string."""
        monkeypatch.setenv("HOME", "/home/user")
        result = replace_env_vars("Path: %home%/Documents")
        assert result == "Path: /home/user/Documents"


class TestResolvePath:
    """Tests for resolve_path function."""

    def test_none_input(self):
        """Test that None input returns None."""
        assert resolve_path(None) is None

    def test_absolute_path_unchanged(self, tmp_path):
        """Test that absolute path is returned as is (after normalization)."""
        # Create a temporary file to ensure path exists
        test_file = tmp_path / "test.txt"
        test_file.write_text("")
        result = resolve_path(str(test_file))
        assert result == str(test_file)

    def test_expands_env_var(self, monkeypatch, tmp_path):
        """Test that environment variables are expanded."""
        monkeypatch.setenv("TEST_PATH", str(tmp_path))
        result = resolve_path("%TEST_PATH%")
        assert result == str(tmp_path)

    def test_expands_env_var_in_path(self, monkeypatch, tmp_path):
        """Test that environment variables in paths are expanded."""
        monkeypatch.setenv("TEST_DIR", str(tmp_path))
        subdir = tmp_path / "subdir"
        subdir.mkdir()
        result = resolve_path("%TEST_DIR%/subdir")
        assert result == str(subdir)

    def test_expands_home_tilde(self, monkeypatch, tmp_path):
        """Test that ~ is expanded to user home directory."""
        home_dir = str(tmp_path / "home")
        monkeypatch.setenv("HOME", home_dir)
        monkeypatch.setenv("USERPROFILE", home_dir)  # Windows uses USERPROFILE
        result = resolve_path("~/Documents")
        expected = str(Path(home_dir) / "Documents")
        assert result == expected

    def test_resolves_relative_path(self, tmp_path, monkeypatch):
        """Test that relative paths are converted to absolute."""
        # Change to tmp_path for this test
        original_cwd = os.getcwd()
        try:
            os.chdir(tmp_path)
            result = resolve_path("relative/path")
            expected = str(tmp_path / "relative" / "path")
            assert result == expected
        finally:
            os.chdir(original_cwd)

    def test_resolves_dot_components(self, tmp_path, monkeypatch):
        """Test that . and .. are resolved."""
        original_cwd = os.getcwd()
        try:
            os.chdir(tmp_path)
            result = resolve_path("./subdir/../other")
            expected = str(tmp_path / "other")
            assert result == expected
        finally:
            os.chdir(original_cwd)

    def test_combined_env_and_home(self, monkeypatch, tmp_path):
        """Test combining environment variables and home expansion."""
        monkeypatch.setenv("MY_VAR", "myvalue")
        home_dir = str(tmp_path)
        monkeypatch.setenv("HOME", home_dir)
        monkeypatch.setenv("USERPROFILE", home_dir)  # Windows uses USERPROFILE
        # When ~ and env vars are combined (~ comes after env var replacement)
        result = resolve_path("~/%MY_VAR%")
        expected = str(Path(home_dir) / "myvalue")
        assert result == expected

    def test_case_insensitive_env_var(self, monkeypatch, tmp_path):
        """Test that environment variable matching is case-insensitive."""
        monkeypatch.setenv("TEST_PATH", str(tmp_path))
        result = resolve_path("%test_path%")
        assert result == str(tmp_path)


class TestCamelCase:
    """Tests for camelCase function."""

    def test_simple_string(self):
        """Test simple string conversion."""
        assert camelCase("hello world") == "helloWorld"

    def test_single_word(self):
        """Test single word."""
        assert camelCase("hello") == "hello"

    def test_with_numbers(self):
        """Test string with numbers."""
        assert camelCase("test 123") == "test123"

    def test_with_special_chars(self):
        """Test string with special characters."""
        assert camelCase("hello-world_test") == "helloWorldTest"

    def test_all_caps(self):
        """Test all caps string."""
        assert camelCase("HELLO WORLD") == "helloWorld"

    def test_mixed_case(self):
        """Test mixed case string."""
        assert camelCase("Hello World Test") == "helloWorldTest"

    def test_empty_string(self):
        """Test empty string."""
        # Empty string will cause IndexError when accessing [1:]
        with pytest.raises(IndexError):
            camelCase("")

    def test_single_character(self):
        """Test single character."""
        assert camelCase("A") == "a"


class TestGetFilenames:
    """Tests for get_filenames function."""

    def test_basic_file_finding(self, tmp_path):
        """Test finding files matching pattern."""
        # Create test files
        (tmp_path / "test1.fits").write_text("")
        (tmp_path / "test2.fits").write_text("")
        (tmp_path / "test3.txt").write_text("")

        result = get_filenames([str(tmp_path)], patterns=[r".*\.fits$"])
        assert len(result) == 2
        assert any("test1.fits" in f for f in result)
        assert any("test2.fits" in f for f in result)

    def test_multiple_patterns(self, tmp_path):
        """Test finding files with multiple patterns."""
        (tmp_path / "test1.fits").write_text("")
        (tmp_path / "test2.xisf").write_text("")
        (tmp_path / "test3.txt").write_text("")

        result = get_filenames([str(tmp_path)], patterns=[r".*\.fits$", r".*\.xisf$"])
        assert len(result) == 2

    def test_recursive_search(self, tmp_path):
        """Test recursive file search."""
        subdir = tmp_path / "subdir"
        subdir.mkdir()
        (tmp_path / "test1.fits").write_text("")
        (subdir / "test2.fits").write_text("")

        result = get_filenames([str(tmp_path)], patterns=[r".*\.fits$"], recursive=True)
        assert len(result) == 2

    def test_non_recursive_search(self, tmp_path):
        """Test non-recursive file search."""
        subdir = tmp_path / "subdir"
        subdir.mkdir()
        (tmp_path / "test1.fits").write_text("")
        (subdir / "test2.fits").write_text("")

        result = get_filenames(
            [str(tmp_path)], patterns=[r".*\.fits$"], recursive=False
        )
        assert len(result) == 1
        assert "test1.fits" in result[0]

    def test_ignore_stash_directories(self, tmp_path):
        """Test that _stash directories are ignored."""
        stash_dir = tmp_path / "some_stash_dir"
        stash_dir.mkdir()
        (stash_dir / "test.fits").write_text("")

        result = get_filenames([str(tmp_path)], patterns=[r".*\.fits$"], recursive=True)
        assert len(result) == 0

    def test_default_pattern(self, tmp_path):
        """Test default pattern for FITS files."""
        (tmp_path / "test1.fits").write_text("")
        (tmp_path / "test2.txt").write_text("")

        result = get_filenames([str(tmp_path)])
        assert len(result) == 1
        assert "test1.fits" in result[0]

    def test_multiple_directories(self, tmp_path):
        """Test searching multiple directories."""
        dir1 = tmp_path / "dir1"
        dir2 = tmp_path / "dir2"
        dir1.mkdir()
        dir2.mkdir()
        (dir1 / "test1.fits").write_text("")
        (dir2 / "test2.fits").write_text("")

        result = get_filenames([str(dir1), str(dir2)], patterns=[r".*\.fits$"])
        assert len(result) == 2

    def test_with_env_vars_in_path(self, tmp_path, monkeypatch):
        """Test that environment variables in paths are replaced."""
        monkeypatch.setenv("TEST_DIR", str(tmp_path))
        (tmp_path / "test.fits").write_text("")

        result = get_filenames(["%TEST_DIR%"], patterns=[r".*\.fits$"])
        assert len(result) == 1
